Hard code cluster.id, add volume for ZK data (#3)
AFAICT, we need to hard-code a cluster ID to avoid issues restarting
kafka using a persistent docker volume to avoid errors like this:

```
kafka.common.InconsistentClusterIdException: The Cluster ID osIH4U8CS7OL_yHqvZ8gOA doesn't match stored clusterId Some(Eog_re46Qo2r4AjXCJZbng) in meta.properties. The broker is trying to join the wrong cluster. Configured zookeeper.connect may be wrong.
mono-kafka-1                   | 	at kafka.server.KafkaServer.startup(KafkaServer.scala:224)
mono-kafka-1                   | 	at kafka.Kafka$.main(Kafka.scala:109)
mono-kafka-1                   | 	at kafka.Kafka.main(Kafka.scala)
mono-kafka-1                   | [2022-10-24 15:00:50,812] INFO shutting down (kafka.server.KafkaServer)
```

Also, add a volume for ZK data, so we can make it persistent over time.